env: # Environt variable to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone repo
    token: "ENCRYPTED[fff4c379af7eb4a0a06a19e87c6ddf0a3a8723f545eab483408177566b1295bb0f4fafc58bc9eef298c8afba7597bf0a]"

task:
    name: AwakenOS build
    timeout_in: 120m
    container:
      image: apon77/aosp:latest
      cpu: 16
      memory: 24G
#     download_ccache_script:
#       - ./download_ccache
    sync_script:
      - ./sync
    build_script:
      - ./build
    upload_ccache_script:
      - ./upload_ccache
